### ISSUE TITLE
Realisieren der Verbindung zur Neo4J-DB

### ISSUE THREAD

**Issue by kevenm94** [volzinnovation/HSPF-Knowledge-Graph#11]

**Comment by volzinnovation** [comment]
Bitte Datenbank Team zuweisen, das sollte eine Aussage treffen wie die Verbindung funktioniert, Betrifft alle Teams (außer Test)

**Comment by AlessandroJaeger** [comment]
Verbindung wurde realisiert und heute (28.11.) beim Standup u.a. auch der Testgruppe präsentiert. 
Dateien werden nach Upload jedoch nicht angezeigt, daher test nicht möglich.

**Comment by volzinnovation** [comment]
Wenn nicht positiv getestet zurück als Todo, nicht schließen

Von meinem iPhone gesendet

Am 28.11.2018 um 18:46 schrieb Alessandro Jaeger <notifications@github.com<mailto:notifications@github.com>>:


Closed #11<https://github.com/volzinnovation/HSPF-Knowledge-Graph/issues/11>.

**Comment by sotten** [comment]
LDAP funktionsfähig und getestet.
