### ISSUE TITLE
Neo4j: Versionsnummer/Komptabilität Cytoscape? Add-Ons?

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#13]
Welche Versionsnummer wird für die Komptabilität benötigt?
Werden noch bestimmte Add-Ons benötigt?
Muss der Server erweitert werden in der Konsole?

**Comment by sotten** [comment]
Latest 2.2 Community Version:
https://neo4j.com/download-thanks/?edition=community&release=2.2.10

**Comment by sotten** [comment]
https://cyneo4j.wordpress.com/new-tutorials/#cypher

**Comment by Stellerc** [comment]
Veraltete Version von Neo4j 2.2.10 nicht für Ubuntu auffindbar.
Neue Version installiert --> Zugriff bei Plugin-Installation verweigert!
![2018-10-23_21h28_57](https://user-images.githubusercontent.com/44025986/47385771-3cd4ef00-d70b-11e8-9d6f-2141e42fa30a.png)

**Comment by sotten** [comment]
![unbenannt10](https://user-images.githubusercontent.com/44020272/47433071-ec5ba100-d79f-11e8-8d7d-43309e52e20d.PNG)
