### ISSUE TITLE
Serververbindung funktioniert noch nicht

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#14]

**Comment by Stellerc** [comment]
Heute getestet, funktioniert aber immer noch nicht

**Comment by volzinnovation** [comment]
Verbindung zu welchem server ist gemeint ?

**Comment by Stellerc** [comment]
Der Server auf dem das Neo4j etc. später laufen soll. Herr Otten hat uns einen Link zu Verfügung gestellt, sobald man eine Remote-Verbindung aufbauen möchte, erscheint eine Fehlermeldung.

**Comment by Stellerc** [comment]
knowledge.stud.ad.fh-pforzheim.de

**Comment by volzinnovation** [comment]
Bitte dieses Ticket Herr Otten zuweisen und einen Screenshot des Fehlers anhängen.

Mit besten Grüßen

Raphael Volz

--
Prof. Dr. Raphael Volz

Professor of Applied Informatics
School of Engineering
HSPF - Pforzheim University

www.hs-pforzheim.de

________________________________________
Von: Stellerc <notifications@github.com>
Gesendet: Montag, 22. Oktober 2018 14:06:31
An: volzinnovation/HSPF-Knowledge-Graph
Cc: Volz, Raphael; Comment
Betreff: Re: [volzinnovation/HSPF-Knowledge-Graph] Serververbindung funktioniert noch nicht (#14)

Der Server auf dem das Neo4j etc. später laufen soll. Herr Otten hat uns einen Link zu Verfügung gestellt, sobald man eine Remote-Verbindung aufbauen möchte, erscheint eine Fehlermeldung.

**Comment by rislingm** [comment]
Problem behoben
