### ISSUE TITLE
Welcher Port soll benutzt werden um Solr zu starten?

### ISSUE THREAD

**Issue by NilsRei** [volzinnovation/HSPF-Knowledge-Graph#17]
/opt/solr-5.5.5/bin$ ./solr start -f

Port 8983 is already being used by another process (pid: 19265)
Please choose a different port using the -p option.

reimoldn@ki_volz:/opt/solr-5.5.5/bin$ ./solr start -p 8984

->Permission denied

**Comment by NilsRei** [comment]
Warum ist kill 19265 nicht erlaubt

**Comment by sotten** [comment]
kill ist sicherlich wegen fehlenden admin rechten nicht erlaubt. Warum wollen Sie solr stoppen?
unter http://141.47.5.51:8983/solr/#/nudel ist solr verfügbar.
