### ISSUE TITLE
Manuelle Abfrage der Profs über Fragebogen

### ISSUE THREAD

**Issue by denizkalafatci** [volzinnovation/HSPF-Knowledge-Graph#18]
Abfrage soll stichprobenartig Fachgebiete + Forschungsaufgaben erfassen
Abfrage soll im späteren Verlauf zum Vergleich mit der Live-Systemabfrage genutzt werden

**Comment by volzinnovation** [comment]
Bitte Fragebogenvorschlag hier anhängen.

**Comment by volzinnovation** [comment]
Bitte auch Anschreibenvorschlag hier einfügen, ohne gutes Anschreiben keine Antwort...

**Comment by volzinnovation** [comment]
Wieviele Leute haben bisher Teilgenommen ?
Alternativ Kompetenzen aus Professorenprofil nehmen, z.B. https://www.hs-pforzheim.de/profile/joergwoidasky/

**Comment by matthiasnuerenberg** [comment]
Von den 10 angefragten Professoren haben wir bisher von 4 Professoren eine Rückmeldung erhalten. Diese werten wir aus und schließen das Issue ab. Aufbauend auf der ersten Abfrage würden wir eine erneute mit angepassten Fragebogen und Anschreiben machen (neues Issue).

**Comment by denizkalafatci** [comment]
Die ausstehenden Rückmeldungen wurden über die Kompetenzfeldsuche ergänzt. Alle Informationen wurden anschließend ausgewertet und in eine Excel-Datei überführt.
[Auswertung Fragebogen_1.xlsx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2576532/Auswertung.Fragebogen_1.xlsx)

**Comment by volzinnovation** [comment]
Danke, aber die datei bitte unmittelbar aus github löschen!

Von meinem iPhone gesendet

Am 13.11.2018 um 15:08 schrieb denizkalafatci <notifications@github.com<mailto:notifications@github.com>>:


Die ausstehenden Rückmeldungen wurden über die Kompetenzfeldsuche ergänzt. Alle Informationen wurden anschließend ausgewertet und in eine Excel-Datei überführt.
Auswertung Fragebogen_1.xlsx<https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2576532/Auswertung.Fragebogen_1.xlsx>
