### ISSUE TITLE
Vorschlag für Attribute aus ActiveDirectory

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#22]
[Vorschlag LDAP.pdf](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2514430/Vorschlag.LDAP.pdf)
Erster Vorschlag für Attribute für die Datenbank. Bei Änderungen bitte melden.

**Comment by volzinnovation** [comment]
Bitte an Otten zuweisen, wenn er das reviewen soll.

**Comment by rislingm** [comment]
siehe ISsue #27
