### ISSUE TITLE
Erstellen der Login-Maske

### ISSUE THREAD

**Issue by kevenm94** [volzinnovation/HSPF-Knowledge-Graph#25]

**Comment by AlessandroJaeger** [comment]
Erste HTML-Grundstruktur erstellt

**Comment by volzinnovation** [comment]
Bitte eindeutige Verantwortung festlegen. Screenshot einfügen und auf Commit Referenzieren

**Comment by kevenm94** [comment]
![image](https://user-images.githubusercontent.com/44026733/47788427-fdf9f700-dd11-11e8-9a04-e2ab598cfbd8.png)

**Comment by volzinnovation** [comment]
Sorry, ist erst Done, wenn im Repository die notwendige Implementierung fertiggestellt ist.

**Comment by kevenm94** [comment]
![image](https://user-images.githubusercontent.com/44026733/48483643-50f4a380-e814-11e8-9523-c3ae8aee6039.png)

**Comment by kevenm94** [comment]
Dateien wurden im Repository hochgeladen
