### ISSUE TITLE
Entscheidung welche ActiveDirectory Attribute in die Datenbankstruktur übernommen werden müssen

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#27]
https://github.com/volzinnovation/HSPF-Knowledge-Graph/blob/master/database/Vorschlag%20LDAP.pdf

**Comment by volzinnovation** [comment]
Bitte eindeutige Verantwortung festlegen

**Comment by kevenm94** [comment]
Wir benötigen

Benutzeranmeldename | userPrincipalName
Passwort | userPassword

**Comment by rislingm** [comment]
Bitte csv Datei aus dem AD ziehen mit diesen Attributen:

https://github.com/volzinnovation/HSPF-Knowledge-Graph/blob/2ff292de43b63b159a1383eb47c16f36200f4636/database/LDAP_Atrribute.xlsx

**Comment by volzinnovation** [comment]
Sorry, aber das Passwort werden wir sicher nicht bereitstellen. Ich wüsste nicht, wofür das benötigt würde.

Mit besten Grüßen

Raphael Volz

--
Prof. Dr. Raphael Volz

Professor of Applied Informatics
School of Engineering
HSPF - Pforzheim University

www.hs-pforzheim.de

________________________________________
Von: Monika Risling <notifications@github.com>
Gesendet: Donnerstag, 1. November 2018 21:20:52
An: volzinnovation/HSPF-Knowledge-Graph
Cc: Volz, Raphael; Comment
Betreff: Re: [volzinnovation/HSPF-Knowledge-Graph] Entscheidung welche ActiveDirectory Attribute in die Datenbankstruktur übernommen werden müssen (#27)

Bitte csv Datei aus dem AD ziehen mit diesen Attributen:

https://github.com/volzinnovation/HSPF-Knowledge-Graph/blob/2ff292de43b63b159a1383eb47c16f36200f4636/database/LDAP_Atrribute.xlsx

**Comment by Stellerc** [comment]
Das war ein Missverständnis. Natürlich muss das Passwort nicht einsehbar sein.

**Comment by volzinnovation** [comment]
Dann bitte aus der Excel rausnehmen und eine neue Version hochladen (unter gleichem Namen), sie nutzen ja ein System, das Versionsverwaltung für sie macht. Also neu abspeichern, commiten, pushen.

Mit besten Grüßen

Raphael Volz

--
Prof. Dr. Raphael Volz

Professor of Applied Informatics
School of Engineering
HSPF - Pforzheim University

www.hs-pforzheim.de

________________________________________
Von: Stellerc <notifications@github.com>
Gesendet: Donnerstag, 1. November 2018 21:52:28
An: volzinnovation/HSPF-Knowledge-Graph
Cc: Volz, Raphael; Comment
Betreff: Re: [volzinnovation/HSPF-Knowledge-Graph] Entscheidung welche ActiveDirectory Attribute in die Datenbankstruktur übernommen werden müssen (#27)

Das war ein Missverständnis. Natürlich muss das Passwort nicht einsehbar sein.

**Comment by rislingm** [comment]
Die neue Datei ohne Passwort ist jetzt hochgeladen unter gleichnamigen Link

**Comment by volzinnovation** [comment]
Fände es übrigens gut, wenn man nicht nur E-Mail, sondern auch Telefon- und Faxnummer der Person anzeigen könnte.

**Comment by sotten** [comment]
AD Auszug per Mail wurde versendet. Bitte kontrollieren und evtl. Nachbesserung fordern.
Die Passwörter sind selbstverständlich nicht im Klartext gespeichert und damit auch ziemlich Nutzlos.

**Comment by volzinnovation** [comment]
Bitte beachten, dass die Daten aus Moodle mit Daten aus AD bezgl. der Person Knoten gemergt werden müssen, d.h. Ein Knoten pro Person hält alle Attribute aus beiden Quellen. 
Dies erreicht man z.B. indem man Excel Sverweise auf Basis einer übereinstimmenden Spalte aufbaut (E-Mail-Adresse ist z.B. beides mal drin und eindeutig).

**Comment by rislingm** [comment]
Daten aus Moodle (1.Tabelle) und AD(jetzige Tabelle) wurden über Neo4j gemergt, haben Sie sich das so vorgestellt?

**Comment by volzinnovation** [comment]
Wie ist mir gleich, ich schaue es mir gerne an

Von meinem iPhone gesendet

Am 08.11.2018 um 13:07 schrieb Monika Risling <notifications@github.com<mailto:notifications@github.com>>:


Daten aus Moodle (1.Tabelle) und AD(jetzige Tabelle) wurden über Neo4j gemergt, haben Sie sich das so vorgestellt?

**Comment by rislingm** [comment]
Wir schicken ihnen dazu das Beispiel per Mail (da personenbezogene Daten)

**Comment by rislingm** [comment]
Antwort zur Mail in #50
