### ISSUE TITLE
Solr Suchmaschine muss fähig sein Stopwords nicht zu berücksichtigen

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#30]

**Comment by volzinnovation** [comment]
Bitte eindeutige Verantwortung festlegen.
Siehe #30, abgebildet in Datei stopwords.txt
Liste ergibt sich aus der Liste der meistvorkommenden Wörter (Luke oder bereitgestellte Java Programme nutzen, um diese zu identifizieren).

**Comment by volzinnovation** [comment]
Gibt wohl ein Encoding Problem mit Umlauten, bitte nochmal drauf schauen, dass die DAtei das richtige Encoding hat (z.B. Programmers Notebook Editor kann so etwas). Die Datei wurde aus einem Linux System eingecheckt...

**Comment by EStromeyer** [comment]
@volzinnovation Encoding wurde verändert. Fehler behoben?

**Comment by vonbuere** [comment]
Mit Hilfe eines VBA Makros werden die Stopwords entfernt, die sich in der erstellten Excel-Tabelle des Java-Programms befinden.
