### ISSUE TITLE
Solr Suchmaschine sollte fähig sein Synonyme in der Suche zu berücksichtigen

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#31]

**Comment by volzinnovation** [comment]
Bitte eindeutige Verantwortung festlegen.

Definition in /var/solr/data/nudel/conf/synonyms.txt (bisher leer)

Werde config Verzeichnis für SolR in GitHub einchecken und dort Versionieren.

**Comment by vonbuere** [comment]
Bei Indexierung werden Wörter auf Ihren Wortstamm gekürzt. Daher wird keine zusätzliche Synonymliste angelegt.

**Comment by volzinnovation** [comment]
So ein Quatsch, bitte nochmal informieren, was das Wort Synonym bedeutet und anhand ähnlicher Worte aus der DTM Synonyme bilden. 
Bei der Indexierung ist übrigens aktuell kein Stemming richtig konfiguriert (nur für Englisch) und Stemming hat gar nix mit Synonymen zu tun.
