### ISSUE TITLE
Solr Suchmaschine sollte die Möglichkeit bieten irrelevante Daten  bei der Suche zu ignorieren

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#32]
Forumsbeiträge in Moodle können von Studenten erstellt werden oder können irrelevant sein, wie z.b. der Eintrag, dass neue Dokumente online sind. Sie sind daher nicht repräsentativ für den Professor und sollten nicht durchsucht werden.

**Comment by volzinnovation** [comment]
Bitte eindeutige Verantwortung zuweisen. 
Aus meiner Sicht ist das  kein Ausschluss beim Indexieren, sondern eine Einschränkung bei der Abfrage

**Comment by volzinnovation** [comment]
Entweder Ausschluss beim Indexieren (Konfiguration Moodle), oder eine Einschränkung bei der Abfrage

**Comment by EStromeyer** [comment]
Areaids (unter anderem Forenbeiträge) sollen bei der Abfrage eingeschränkt werden.

**Comment by NilsRei** [comment]
Durch Anpassung der Suche von Field "_text_" zu Field "solr_filecontent" werden ca. 260.00 irrelevante Begriffe nicht durchsucht

**Comment by vonbuere** [comment]
Der folgende Link stellt die Suchanfrage dar, die der Browsergruppe übermittelt wurde in Issue #54. In der Suchanfrage werden die nicht benötigten Areaids ausgeschlossen. 


http://141.47.5.51:8983/solr/nudel5/select?q=xml%0ANOT%0Aareaid%3Amod_forum-post%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A%0A&rows=0&wt=json&indent=true&facet=true&facet.field=courseid&facet.limit=3&facet.mincount=5&facet.offset=0
