### ISSUE TITLE
Solr muss fähig sein Daten zu indizieren

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#33]
Solr muss alle Dateiinhalte indizieren, sodass sie für die Suche zur Verfügung stehen.

**Comment by vonbuere** [comment]
In der LOG Datei für die Indexierung gibt es Fehlermeldungen. Es muss überprüft werden, ob trotzdem zuverlässige Ergebnisse erzielt werden können oder ob Fehler behoben werden müssen.

**Comment by volzinnovation** [comment]
Bitte eindeutiges verantwortliches Team-Mitglied zuweisen

**Comment by NilsRei** [comment]
Solr-Abfrage kann mit den indizierten Daten durchgeführt werden.
