### ISSUE TITLE
Solr Suchmaschine muss Course ID zu Themenanfragen zuordnen können.

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#34]
Mit Hilfe der Solr Suchmaschine soll zu einer Themenabfrage die Course IDs ermittelt werden, in denen der Suchbegriff häufig vorkommt. Die Course IDs werden an die Datenbank übergeben, in der sie den Professoren zugeordnet werden müssen.

**Comment by volzinnovation** [comment]
Siehe  https://github.com/volzinnovation/HSPF-Knowledge-Graph/blob/master/index/de.hspf.ai.kg/src/main/java/Searcher.java

**Comment by volzinnovation** [comment]
Bitte Assignment des Todos klären (ein verantwortliches Team-Mitglied)

**Comment by vonbuere** [comment]
Searcher.java kann Themenanfrage den Coursids zuordnen
