### ISSUE TITLE
Suchmaske Analog zu Google erstellen

### ISSUE THREAD

**Issue by Schello7** [volzinnovation/HSPF-Knowledge-Graph#35]
Es soll eine Suchmaske analog zu Google erstellt werden. 
Bei der Suche nach einem Thema soll das Thema plus die Profs, welche das Thema bedienen als Ergebnis angezeigt werden.
Alternativ soll nach Profs gesucht werden können. Hier soll der Prof plus dessen Themen angezeigt werden.
@Katsanidis 
@oezdinya

**Comment by volzinnovation** [comment]
Sehe keine lauffähige Version auf dem Server deployed, folglich nicht done.

**Comment by volzinnovation** [comment]
ebenfalls gemäß unserer Absprache vom letzten Standup, wenn "fertig" aus Entwickungssicht der verantwortlichen Person aus dem Testteam zu ordnen, Testprotokoll ausfüllen. Diese macht dann den Test und erklärt das im positiven Fall als Fertig, sonst mit Anmerkung zurück.-

**Comment by denizkalafatci** [comment]
Test wurde durchgeführt. Ergebnis siehe Protokoll.
[testprotokoll_Browser_Issue35.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2621045/testprotokoll_Browser_Issue35.docx)

**Comment by volzinnovation** [comment]
Leider nicht closed, sondern zu bearbeiten, Test war ja nicht erfolgreich
