### ISSUE TITLE
ConfigMask bitte unter config Verzeichnis ziehen

### ISSUE THREAD

**Issue by volzinnovation** [volzinnovation/HSPF-Knowledge-Graph#37]

**Comment by AlessandroJaeger** [comment]
Daten sind im config Verzeichnis. 
Ich kann dass erstellte Verzeichnis ConfigMask nicht löschen.

**Comment by volzinnovation** [comment]
Habe ConfigMask gelöscht
(einfach Verzeichnis löschen und dann Commiten und Pushen)
