### ISSUE TITLE
git-clone auf www/html/graphbrowser

### ISSUE THREAD

**Issue by sotten** [volzinnovation/HSPF-Knowledge-Graph#41]
Klon das Repository in das Verzeichnis www/html/graphbrowser

**Comment by volzinnovation** [comment]
Configseite kann gerne eigenen Ordner nutzen

**Comment by sotten** [comment]
@AlessandroJaeger @Katsanidis @oezdinya 
Zugriff für Browser Team: 141.47.5.51/HSPF-Knowledge-Graph/browser/
Zugriff für Config Team: 141.47.5.51/HSPF-Knowledge-Graph/config

Pull vom Repository auf Server:
Im Pfad var/www/html/HSPF-Knowledge-Graph folgendes ausführen:
git pull https://github.com/volzinnovation/HSPF-Knowledge-Graph.git
