### ISSUE TITLE
Erstellen der Seite mit den Themen des Professors

### ISSUE THREAD

**Issue by kevenm94** [volzinnovation/HSPF-Knowledge-Graph#44]

**Comment by kevenm94** [comment]
![image](https://user-images.githubusercontent.com/44026733/48483747-9913c600-e814-11e8-97b3-6b4142e17548.png)

**Comment by AlessandroJaeger** [comment]
Wurde heute beim Standup vorgestellt (28.11.) und für funktionsfähig befunden.
