### ISSUE TITLE
Datenstruktur für Kurse mit richtigen Attributen anpassen

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#48]
Hierfür werden die Attribute von der Index Gruppe nötig
Anschließend einfügen in Datenbank

**Comment by vonbuere** [comment]
Wie besprochen benötigen wir die Attribute courseid und themen.

**Comment by volzinnovation** [comment]
Thema ist kein Attribut, sondern ein eigenständiger Knoten
Es gibt eine Relation (Kante im Graph) zwischen Prof -> Thema, analog Prof -> Kurs und das ist eine n:m beziehung
Der Knoten Thema hat mindestens ein Attribut "name", sicher aber noch zusätzliche Attribute, wie Erzeugungsdatum
Jede Ausprägung der Kante Prof -> Thema, z.B. (Volz -> XML) hat ebenfalls Attribute, z.b. wer hat das Erzeugt (Index oder Config Seite), Ist das ein Einschluss oder Ausschluss (Prof. hat das Thema gelöscht), und weitere z.B. Zeitstempel, wer die Info wann angelegt hat.

**Comment by rislingm** [comment]
Danke für die Antwort.
Folgen sind ja Verantwortlichkeit Index-Gruppe.
