### ISSUE TITLE
Hochladen der lokalen Dateien in den Server (inklusive Anpassen)

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#50]

**Comment by volzinnovation** [comment]
Gibt noch Probleme mit dem Upload der Professoren Daten aus dem ActiveDirectory im Falle von Sonderzeichen, z.B:

{
  "IDprof": 24,
  "firstname": "J�rgen",
  "alias": "juergen.bauer",
  "company": "T-P",
  "Typ": "Professor",
  "officephone": "+497231286165",
  "department": "T2.3.13",
  "email": "juergen.bauer@hs-pforzheim.de",
  "lastname": "Bauer"
}

**Comment by rislingm** [comment]
Ok,
company wurde in school und role aufgeteilt, 
department in office umbenannt und 
Sonderzeichen (ä,ü,ö,ß) entfernt

**Comment by volzinnovation** [comment]
Bitte Person aus Testgruppe zuweisen, Testprotokoll ausfüllen, und in Test Spalte verschieben

**Comment by volzinnovation** [comment]
"role": "M" ist nicht vom Typ "Professor" sondern "Mitarbeiter". Typ und Role sind redundant.
  "Typ": "Professor" ist "role":"P"
"Typ": "Mitarbeiter" ist "role":"M"

**Comment by volzinnovation** [comment]
Beispiele ohne "role" beim Import sind externe Lehrbeauftragte, z.b.

  "IDprof": 11,
  "alias": "marco.melle",
  "Typ": "Professor",
  "email": "marco.melle@hs-pforzheim.de"

**Comment by rislingm** [comment]
wird übernommen, wie heute in SCRUM besprochen ( nur role & alles auf Englisch)

**Comment by rislingm** [comment]
Test findet in #59 statt
Änderungen von oben übernommen
