### ISSUE TITLE
Verantwortlichkeit für Querys mit Schnittstellen zu Datenbank

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#51]

**Comment by rislingm** [comment]
Vorschlag unsererseits:
Wir machen die Verbindung von Themen zu Prof in der Datenbank für die Solr-Gruppe
Die Abfrage der Daten macht die Solr Gruppe (Index)
Wir machen die Schnittstelle zur Browser Gruppe (nochmal Absprache mit der Gruppe)
Die Schnittstelle zur Config Gruppe macht die Config Gruppe
Bitten um zeitnahe Rückmeldung ob das so für alle okay ist?

**Comment by vonbuere** [comment]
Vorschlag unsererseits: 
Die Daten für die Zuordnung Themenfeld zu Course_Id machen wir (Index). Die Datenbankgruppe macht die Verbindung dann zur Prof_Id. Die weitere Abfarge wird von der Browser Gruppe gestaltet.

**Comment by Stellerc** [comment]
weshalb die änderung? also was ist euer gedanke dabei?

**Comment by vonbuere** [comment]
Eingabe Professor in Suchfeld:
Wir liefern euch einmalig zu jeder Course_ID die Topthemen, welche in eurer Datenbank dann mit den Prof_IDs verbunden werden. Diese Daten werden dann nur noch von der Browser Gruppe von der Datenbank abgerufen. 

Eingabe Thema in Suchfeld:
Wird ein Thema in die Suchmaske eingegeben durchsucht Solr das Moodle und liefert die Top Course-IDs. Diese Course-IDs werden dann von uns in die Datenbank geschrieben (Set-Befehl o.ä.) und von der Datenbank wieder mit den Prof_IDs verbunden. 
Noch zu klären:  wird die Endabfrage von der Datenbank von der Browsergruppe getätigt?

**Comment by NilsRei** [comment]
Es gibt ja zwei Arten der Suche. Einmal wird ein Themenfeld z.B. XML in die Suchmaske gegeben: 

Eingabe Thema in Suchfeld:
Wird ein Thema in die Suchmaske eingegeben durchsucht Solr das Moodle und liefert die Top Course-IDs. Diese Course-IDs werden dann von uns in die Datenbank geschrieben (Set-Befehl o.ä.) und von der Datenbank wieder mit den Prof_IDs verbunden und ausgegeben.

Die zweite Art der Suche gestaltet sich wenn man die Themenfelder eines Professors sucht:

Eingabe Professor in Suchfeld:
Wir (Solr) liefern der Datenbankgruppe einmalig zu jeder Course_ID die Topthemen, welche in eurer Datenbank dann mit den Professoren verbunden sind. Diese Daten werden dann  von der Browser_Gruppe von der Datenbank abgerufen. 

Um in diesen zwei Fällen zu unterscheiden wäre es möglich eine Abfrage zu schreiben in der das Suchwort mit der Proffessorenliste abgeglichen wird, ist das Suchwort nicht enthalten greift Suchabfrage: "Eingabe Thema in Suchfeld". Nach Anfrage bei Herr Volz fällt dies in das Aufgabengebiet der Browsergruppe

**Comment by AlessandroJaeger** [comment]
Für die Config-Gruppe geht das in Ordnung!
Uns ist momentan noch nicht klar, um was für eine Datenbank es sich handelt, innerhalb derer die Themen geändert werden können. Welche Datenbank ist dies und wie lässt sich darauf zugreifen?

**Comment by Stellerc** [comment]
Zugriff können wir euch einrichten. Die DB läuft seit gestern erst wieder. Zugänge werden kreiert und an euch weitergeleitet.

**Comment by Stellerc** [comment]
@AlessandroJaeger siehe Issue #49 
@vonbuere zu deinem/eurem Vorschlag. Das geht soweit i. O., beachtet bitte dass die jetzige Verbindung zwischen **Prof** und **Kurs** besteht, ergo nicht zwischen **Thema** und **Prof**. Diese Verbindung muss dann durch eure Query (Set-Befehl) hergestellt werden.

**Comment by volzinnovation** [comment]
Wird in Standup heute diskutiert
