### ISSUE TITLE
Verantwortlichkeit für Übergabe der Suchfeldeingabe vom Browser an Solr

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#54]
Übergabe des Suchbegriffs aus Suchfeld an Solr Suchmaschine muss abgeklärt werden. Hierfür müssen die Übergabeparameter festgelegt werden.

**Comment by EStromeyer** [comment]
Wie Abgesprochen der vorläufiger http Code für die Suchfeldeingabe. 

http://141.47.5.51:8983/solr/nudel5/select?q=xml%0ANOT%0Aareaid%3Amod_forum-post%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A%0A&rows=0&wt=json&indent=true&facet=true&facet.field=courseid&facet.limit=3&facet.mincount=5&facet.offset=0

Aktueller Suchbegriff xml, muss durch Eingabefeld von euch befüllt werden.
Gibt Aktuelles die Top 3 courseids für xml aus. Wird im laufe der Woche noch so angepasst, das die Top Professoren angezeigt werden.

**Comment by NilsRei** [comment]
Hier der finale Link, mit der Zuordung auf die owneruserid (Profid) . Owneruserid=0 wird ausgegrenzt.

http://141.47.5.51:8983/solr/nudel5/select?q=xml%0ANOT+owneruserid%3A0%0ANOT%0Aareaid%3Amod_forum-post%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A%0A&rows=0&wt=json&indent=true&facet=true&facet.field=owneruserid&facet.limit=3&facet.mincount=5&facet.offset=0
