### ISSUE TITLE
Suchmaske soll über einen Button geschlossen werden können

### ISSUE THREAD

**Issue by Schello7** [volzinnovation/HSPF-Knowledge-Graph#56]
Der Graph ist hinter der Suchmaske zu sehen. Damit der Nutzer direkt im Graph navigieren kann, soll die Suchmaske mithilfe eines Buttons verbergt werden können (Abstimmung mit Herrn Otten).
![showsearch](https://user-images.githubusercontent.com/44027048/48363558-782d6280-e6a6-11e8-9437-db6a7bd960a5.png)

**Comment by denizkalafatci** [comment]
Funktion wurde fehlerfrei getestet. Ergebnis siehe Testprotokoll
[testprotokoll_Browser_Suchmaske schließen.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2608934/testprotokoll_Browser_Suchmaske.schliessen.docx)
