### ISSUE TITLE
Funktionsfähige Datenbankmodule sollten getestet werden

### ISSUE THREAD

**Issue by denizkalafatci** [volzinnovation/HSPF-Knowledge-Graph#59]
Aus dem StandUp vom 07.11 konnte die Information mitgenommen werden, dass es testbare Zwischenstände im Modul Datenbank gibt.

Um festzustellen was genau getestet werden kann, sollte die Datenbank-Gruppe im **Testprotokoll** die Felder unter dem Punkt **Testinhalte** bitte vorab ausfüllen. Das entsprechende Dokument liegt unter "Code\testing".

Das ausgefüllte Dokument am besten unter dieses Issue posten.

**Comment by Stellerc** [comment]
[testprotokoll_Datenbank.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2577525/testprotokoll_Datenbank.docx)

**Comment by denizkalafatci** [comment]
Test wurde entsprechend dem Testprotokoll durchgeführt und dokumentiert. Die Ergebnisse werden im StandUp am 21.11 vorgestellt.
