### ISSUE TITLE
Anschreiben und Fragebogen sollte angepasst werden

### ISSUE THREAD

**Issue by matthiasnuerenberg** [volzinnovation/HSPF-Knowledge-Graph#60]
Aufgrund einer Teilnahmequote von nur 40% und Datenschutzbedenken wird das Anschreiben und der Fragebogen angepasst. Die entsprechenden Dokumente stehen zur Prüfung bereit.
[Anschreiben_fragebogenV2.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2576491/Anschreiben_fragebogenV2.docx)
Fragebogen: https://goo.gl/forms/LR21OstjdEPRTlgT2

**Comment by volzinnovation** [comment]
**WICHTIG:** Bitte von weiteren Anfragen erst einmal absehen. Bitte zwingend bei solchen Aktionen BCC verwenden, niemals per CC den ganzen Verteiler kommunizieren. (a) Sind die Ansprechpartner einer Mailingliste vertraulich (b) kann dann niemand "an alle" Antworten und seinen Unmut an die ganze Gruppe kommunizieren.
