### ISSUE TITLE
Javaabfrage schreiben, die zu jeder courseid die HighfrequenzTerms zuweisen

### ISSUE THREAD

**Issue by NilsRei** [volzinnovation/HSPF-Knowledge-Graph#61]
Wir möchten den TermCounter so anpassen, damit er nicht die häufigsten Wörter in allen Dateien ausgibt, sondern unterteilt in die verschiedenen courseid's. 
![highfreqterm](https://user-images.githubusercontent.com/44026747/48425567-61017a00-e765-11e8-9204-d4e07e3b74e6.JPG)
Ist die Annahme richtig, dass diese HighFreqTerms-Class die Liste der Top Terms befüllt?
Könne wir diese Class für unsere Aufgabe anpassen oder müssen wir eine andere Class verwenden?

**Comment by vonbuere** [comment]
Term Counter erstellt die DocumentTermMatrix
