### ISSUE TITLE
Den Searcher.java anpassen damit er bestimmte "areaid" nicht sucht

### ISSUE THREAD

**Issue by NilsRei** [volzinnovation/HSPF-Knowledge-Graph#62]
Die Abfrage soll dahingehend angepasst werden, damit  bestimmte areaids nicht gefunden werden.
Ist der org.apache.lucene.queryparser.classic.QueryParser hierfür der richtige ?
Wie ist die Query zu erweitern, dass man  diese bestimmte "Field:Inhalt" ausschließen kann?

**Comment by volzinnovation** [comment]
Sorry das ist ihre Aufgabe die richtige Quere zu formulieren, ich habe Ihnen freundlicherweise Beispiele geschrieben, die man auch selbst aus der Dokumentation von Solr hätte schreiben können...

Von meinem iPhone gesendet

Am 14.11.2018 um 00:18 schrieb NilsRei <notifications@github.com<mailto:notifications@github.com>>:


Assigned #62<https://github.com/volzinnovation/HSPF-Knowledge-Graph/issues/62> to @volzinnovation<https://github.com/volzinnovation>.

**Comment by volzinnovation** [comment]
Searcher ist ein **Beispielprogramm**, das direkt auf der Indexdatei operiert. Alternativ dazu kann man dasselbe auch erreichen, in dem man mit dem SolRServer spricht, dafür gibt es verschiedene Bibliotheken in der Programmiersprache ihrer Wahl (siehe Seite 598 von Solr Ref Guide 5.5), wo sie das entsprechend auch lösen können. Ausschluss eines Feldes ist durchaus möglich, siehe auch die Felddefinitionen. Sie suchen aktuell im Feld "_text_", das Feld "_text_" sammelt per Copy Befehl am Ende der Schema Definition sachen aus allen anderen Feldern.

Sie können also entweder ein (1) anderes Feld durchsuchen, oder eine (2) Menge von anderen Feldern, oder den (3) Copy Befehl abändern, der _text_ befüllt, etc. (1) und (2) wären Dinge, die bei der Abfrage passieren (Query Time), (3) eine Lösung, die bei der Indexierung passiert. (1) und (2) lassen sich also leichter abändern, da sie die Daten nicht neu indizieren müssen. Bei (3) muss man nach der Änderung den Index neu bilden. Daher wäre meine Präferenz, sich mit der Query Syntax zu beschäftigen. Wie die funktioniert ist wohldokumentiert.

Siehe http://lucene.apache.org/core/5_5_0/queryparser/org/apache/lucene/queryparser/classic/QueryParser.html (für die Klasse QueryParser, die sie aktuell verwenden)

Siehe http://lucene.apache.org/core/5_5_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description für die eigentlichen Möglichkeiten zur Abfrage, die sie verwenden können.

**Comment by vonbuere** [comment]
Searcher.java wird hierfür nicht mehr verwendet. Problemstellung wird in #32 gelöst.
