### ISSUE TITLE
Bereitstellung Neo4j Daten für andere Gruppen

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#66]
Die Datenbank wurde frisch aufgesetzt und ist unter dem Port 7474 erreichbar. 
Benutzernamen und Passwörter sind verteilt worden (SCRUM 14.11.18).

UML folgt (hier Auflistung der genauen Attribute zu sehen)
Installationsanleitung unter #65

**Comment by Stellerc** [comment]
![uml](https://user-images.githubusercontent.com/44025986/48627370-b54e6900-e9b4-11e8-9e81-cf92321588e3.PNG)

Hier das UML-Diagramm der jetzigen DB.

**Comment by rislingm** [comment]
Scheint zu passen, wurde bei SCRUM 21.11.18 besprochen
