### ISSUE TITLE
Verbindung zur Neo4j Datenbank über Server

### ISSUE THREAD

**Issue by kevenm94** [volzinnovation/HSPF-Knowledge-Graph#69]

**Comment by kevenm94** [comment]
@sotten Ich habe auf dem Server in der config.yml Datei die Verbindung zur Neo4j Datenbank eingetragen.
![image](https://user-images.githubusercontent.com/44026733/48672542-6715a300-eb37-11e8-8a18-c67eb37bb41a.png)
Ich kann es jedoch nicht im Browser anzeigen lassen, hier kommt folgende Meldung 
![image](https://user-images.githubusercontent.com/44026733/48672559-a47a3080-eb37-11e8-9acf-84c92ec197b7.png) habe ich vl die falsche Adresse eingegeben ?

**Comment by sotten** [comment]
@kevenm94 VPN an?
den Port 8080 öffnen:

php -S 141.47.5.51:8080

**Comment by kevenm94** [comment]
@sotten ja hatte ich bereits davor gemacht

**Comment by kevenm94** [comment]
Problem wurde gelöst - Verbindung zur Testdatenbank steht mittlerweile.
