### ISSUE TITLE
Inhalte der Datenbank sollen testdatenfrei sein

### ISSUE THREAD

**Issue by rislingm** [volzinnovation/HSPF-Knowledge-Graph#74]
In den letzten Wochen wurden immer wieder neue, nicht relevante Daten eingefügt, welche nicht zum Knowledge-Graph gehören. Wir bitten euch ab jetzt keine Testdaten mehr hochzuladen. Wir werden am Mittwoch die Datenbank wieder neu generieren und alle Testdaten somit löschen. Sobald die Daten der anderen Gruppen hochgeladen sind, ist eine neue Generierung sehr zeitaufwendig und sollte vermieden werden. Ab nächsten Mittwoch könnt ihr eure Queries auf den Server hochladen. Wir bitten euch auch eure Queries auf das Github für einfachere Replikation hochzuladen, wenn ihr soweit seid.

**Comment by sotten** [comment]
Zugangsdaten zum Testserver sind per E-Mail verteilt worden

**Comment by rislingm** [comment]
Datenbank wurde frisch aufgesetzt, der Fehler mit den ß wurde hoffentlich behoben.
@denizkalafatci bitte testen

**Comment by denizkalafatci** [comment]
Fehler ist leider noch da. Grund und Lösungsvorschlag siehe Testprotokoll
[testprotokoll_Datenbank_v2.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2608407/testprotokoll_Datenbank_v2.docx)

**Comment by rislingm** [comment]
Da ist wohl ein Fehler unterlaufen.
Wir hatten erwähnt, dass alle Sonderzeichen grundsätzlich ersetzt wurden, da das Neo4j diese nicht verarbeiten kann.
ß wird zu ss, ä zu ae usw.
Also wenn man nach Oßwald sucht wird daraus Osswald(ist ja auch bei ELearning Kursen so)
Unser Test funtioniert mit Osswald:
![image](https://user-images.githubusercontent.com/44026734/48909289-26869400-ee6d-11e8-90ab-70ad4d572f67.png)

**Comment by rislingm** [comment]
@volzinnovation fyi
