### ISSUE TITLE
DokumentTermMatrix mit ProfID verbinden und anpassen

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#77]
Die in #38 erstellte Dokument Term Matrix enthält eine Spalte CourseID, die zur passenden ProfID verbunden werden muss. Im weiteren Verlauf muss die Matrix so angepasst werden, dass jedem Prof seine Fachgebiete zugeordnet werden können.

**Comment by vonbuere** [comment]
Die Verbindung ProfID zu Courseid konnte hergestellt werden. Jedoch sind manche Felder mit "???" befüllt.

**Comment by NilsRei** [comment]
Der TermCounter erstellt eine CSV-Datei.
Diese Makros ermöglichten die dynamische Erstellung einer CSV-Datei. Die resultierende Datei ist sortiert und bearbeitet, sodass die 5 TopThemen zu jedem Prof gefiltert werden. Diese Datei kann direkt in die Datenbank geladen werden.
