### ISSUE TITLE
Searcher.java muss die Daten im richtigen Format übergeben

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#78]
Der Seracher muss so angepasst werden, damit nur die ProfID ausgegeben wird und an der richtigen Schnittstelle übergeben wird.

**Comment by volzinnovation** [comment]
Alternative zum Nachdenken: Neues Feld profid in Solr anlegen und dieses Feld für alle Dokumente mit courseid befüllen (über ein kleines Programm), siehe https://lucene.apache.org/solr/guide/6_6/updating-parts-of-documents.html (Atomic Updates). Dann braucht man keinen Endpunkt und alle benötigten Daten für die Suche sind direkt in Solr Index.

Sonst muss man halt einen kleinen Web Service schreiben und an einem Endpunkt betreiben und eigene Schnittstelle zu Browser Team basteln.

**Comment by EStromeyer** [comment]
Code wurde in #54 übergeben an Browserteam übergeben.
