### ISSUE TITLE
Testprotokoll- Browser Abfrage Neo4J

### ISSUE THREAD

**Issue by Katsanidis** [volzinnovation/HSPF-Knowledge-Graph#79]
Letzte Woche wurden die Abfragen erstellt. Die Testgruppe kann diese nun in Neo4J überprüfen.

**Comment by Schello7** [comment]
[testprotokoll_Browser_Abfragen.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2603988/testprotokoll_Browser_Abfragen.docx)

**Comment by denizkalafatci** [comment]
Abfragetest wurde fehlerfrei durchgeführt. Ergebnis siehe Testprotokoll
[testprotokoll_Browser_Abfragen_Neu_v2.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2608807/testprotokoll_Browser_Abfragen_Neu_v2.docx)
