### ISSUE TITLE
Datenim-/export

### ISSUE THREAD

**Issue by vonbuere** [volzinnovation/HSPF-Knowledge-Graph#8]
In welchem Datenformat erhalten wir die Daten und in welcher Form müssen die Suchabfragen an die Datenbank weitergegeben werden?

**Comment by volzinnovation** [comment]
Verantwortung festlegen.
Schnittstelle mit Datenbank Team besprechen

**Comment by volzinnovation** [comment]
Abstimmen mit Datenbank-Team. 
"Datenimport" Minimal benötigt man eine Abfrage mit Input (WHERE Clause by SQL) KursID und Output ProfID, dies wird nicht importiert, sondern immer adhoc abgefragt, deshalb ist dieser Issue falsch benamt, würde die beiden Aufgaben auch unbedingt trennen.

Beispielquery (aus neo4j Tutorial) als Vorlage:



MATCH (m:Movie {title: 'Forrest Gump'})<-[:ACTS_IN]-(a:Actor)

RETURN a.name, a.birthplace



"Datenexport" hat etwas mit der DTM zutun, und erzeugt Topic Knoten und eine Topic->Person beziehung, Datenbank-Team kann hierfür Datenbankschnittstelle öffnen und sie benutzen die Querysprache Cypher, siehe Link https://neo4j.com/developer/cypher-query-language/#_create_your_friends

Beispiel

CREATE (you:Person {name:"You"})
RETURN you

CREATE creates nodes with labels and properties.

You like Neo4j, right?

Let’s find ourselves and add a new relationship to a new node.

MATCH  (you:Person {name:"You"})
CREATE (you)-[like:LIKE]->(neo:Database {name:"Neo4j" })
RETURN you,like,neo

**Comment by EStromeyer** [comment]
Wird in Issue #51 geklärt.

**Comment by vonbuere** [comment]
Verantwortlichkeit wurde mit Datenbank Team besprochen
