### ISSUE TITLE
Neo4J Abfragen beschleunigen

### ISSUE THREAD

**Issue by volzinnovation** [volzinnovation/HSPF-Knowledge-Graph#80]
Nutzung von Index Strukturen, siehe https://neo4j.com/docs/developer-manual/current/cypher/schema/index/

**Comment by rislingm** [comment]
Befehle unter https://github.com/volzinnovation/HSPF-Knowledge-Graph/blob/master/database/Index-Befehle.txt

Wird auf DB gespielt, Status folgt

**Comment by rislingm** [comment]
funktioniert auch mit Beispielen, 
![image](https://user-images.githubusercontent.com/44026734/48849041-ce388f00-eda5-11e8-9080-03d57390a77b.png)

**Comment by rislingm** [comment]
@Testgruppe: Bitte prüfen, ob Abfragen mit Index klappen

**Comment by denizkalafatci** [comment]
Abfragen mit Index wurden fehlerfrei getestet.
[testprotokoll_Datenbank-index.docx](https://github.com/volzinnovation/HSPF-Knowledge-Graph/files/2608716/testprotokoll_Datenbank-index.docx)
