### ISSUE TITLE
Falsche Topics bei Prof

### ISSUE THREAD

**Issue by sotten** [volzinnovation/HSPF-Knowledge-Graph#86]
Falsche Topics bei Prof. Volz. Bei folgender Abfrage:

http://141.47.5.51:8983/solr/nudel5/select?q=see%0ANOT%0Aareaid%3Amod_forum-post%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A%0A&rows=0&wt=json&indent=true&facet=true&facet.field=courseid&facet.limit=3&facet.mincount=5&facet.offset=0

taucht die Prof ID von Prof. Volz nicht auf. In der Neo4J Datenbank ist das Topic aber dem Prof zugeordnet:

![image](https://user-images.githubusercontent.com/44020272/49740966-b1e98d00-fc95-11e8-8e4f-a19991f5b303.png)

wo liegt die CSV die ins Neo4J geladen wurde?

**Comment by EStromeyer** [comment]
Hallo Herr Otten,

die Abfrage die verwendet wird ist nicht die aktuelle wie in #54 kommuniziert. Die Verwendete Abfrage sortiert noch nach courseid und nicht nach userownerid. Wenn der aktuelle Link verwendet wird:

http://141.47.5.51:8983/solr/nudel5/select?q=See%0ANOT%0Aareaid%3Amod_forum-post%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A%0A&rows=0&wt=json&indent=true&facet=true&facet.field=courseid&facet.limit=3&facet.mincount=5&facet.offset=0

Wir Herr Volz ebenfalls noch nicht gefunden, da nur die Top 3 Professoren zu diesem Thema ausgegeben werden. Volz ist aber in der Gesamtübersicht aber erst auf Plaz 10 hier zu sehen

http://141.47.5.51:8983/solr/nudel5/select?q=See%0ANOT+owneruserid%3A0%0ANOT%0Aareaid%3Amod_forum-post%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A%0A&rows=0&wt=json&indent=true&facet=true&facet.field=owneruserid&facet.limit=100&facet.mincount=0&facet.offset=0

Note und Video werden durch diese Suche ebenfalls nicht gefunden. Die liegt aber dran, dass diese Begriffe in den forum_posts enthalten sind, die auf dem anderen Weg ja nicht ausgeschlossen werden. Hier der Code ohne die Ausgrenzung der forum_posts

http://141.47.5.51:8983/solr/nudel5/select?q=Note%0ANOT%0Aareaid%3Amod_forum-activity%0ANOT%0Aareaid%3Amod_label-activity%0ANOT%0Aareaid%3Amod_glossary-entry%0ANOT%0Aareaid%3Amod_page-activity%0ANOT%0Aareaid%3Amod_choice-activity%0ANOT%0Aareaid%3Amod_scorm-activity%0ANOT%0Aareaid%3Amod_data-activity%0ANOT%0Aareaid%3Amod_wiki-collaborative_page%0ANOT%0Aareaid%3Amod_book-activity%0ANOT%0Aareaid%3Amod_chat-activity%0ANOT%0Aareaid%3Amod_glossary-activity%0ANOT%0Aareaid%3Amod_wiki-activity%0ANOT%0Aareaid%3Amod_survey-activity%0ANOT%0Aareaid%3Amod_imscp-activity%0ANOT%0Aareaid%3Achange.me%0A&rows=0&wt=json&indent=true&facet=true&facet.field=owneruserid&facet.limit=100&facet.mincount=0&facet.offset=0

**Comment by sotten** [comment]
Wo liegt die Datei mit der die Neo4J befüllt worden ist? Weshalb sind die Forums Post nicht ausgeklammert in der Datei?
